const s = {
  dropZone: {
    border: "2px dashed #D1D5DB",
    borderRadius: 12,
    padding: 48,
    textAlign: "center",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  error: {
    background: "#fef2f2",
    color: "#dc2626",
    padding: "10px 14px",
    borderRadius: 8,
    fontSize: 13,
    marginBottom: 12,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  stepHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    flexWrap: "wrap",
    gap: 8,
  },
  th: {
    padding: "8px 10px",
    textAlign: "left",
    fontWeight: 600,
    fontSize: 11,
    textTransform: "uppercase",
    color: "#6B7280",
    letterSpacing: "0.3px",
  },
  td: {
    padding: "8px 10px",
  },
  select: {
    padding: "6px 10px",
    borderRadius: 6,
    border: "1px solid #d1d5db",
    fontSize: 13,
    minWidth: 180,
    background: "#fff",
  },
  confBadge: {
    padding: "2px 8px",
    borderRadius: 10,
    fontSize: 11,
    fontWeight: 600,
  },
  qbBadge: {
    display: "inline-block",
    marginLeft: 8,
    padding: "2px 8px",
    background: "#dbeafe",
    color: "#1e40af",
    borderRadius: 10,
    fontSize: 11,
    fontWeight: 600,
  },
  typeBadge: {
    display: "inline-block",
    marginLeft: 8,
    padding: "2px 8px",
    background: "#FDF8F0",
    color: "#6B1E1E",
    borderRadius: 10,
    fontSize: 11,
    fontWeight: 600,
  },
  qbNotice: {
    background: "#eff6ff",
    border: "1px solid #bfdbfe",
    borderRadius: 8,
    padding: "10px 14px",
    fontSize: 13,
    color: "#1e40af",
    marginBottom: 16,
  },
  summaryBox: {
    background: "linear-gradient(135deg, #FDF8F0 0%, #F5EDE3 100%)",
    border: "1px solid rgba(107, 30, 30, 0.08)",
    borderRadius: 10,
    padding: 16,
    marginBottom: 16,
  },
  previewCard: {
    background: "#FDF8F0",
    borderRadius: 8,
    padding: "12px 14px",
    textAlign: "center",
    border: "1px solid #E5E0DA",
  },
  doneBox: {
    textAlign: "center",
    padding: 40,
    background: "#f0fdf4",
    borderRadius: 12,
    border: "1px solid #bbf7d0",
  },
  editInput: {
    padding: "4px 8px",
    borderRadius: 4,
    border: "1px solid #E5E0DA",
    fontSize: 12,
    width: "100%",
    background: "#fff",
  },
  // ─── Queue Panel ──────────────────────────────────────────
  queuePanel: {
    border: "1px solid #E5E0DA",
    borderRadius: 12,
    background: "#fff",
    overflow: "hidden",
  },
  queueHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "14px 16px",
    borderBottom: "1px solid #f1f5f9",
    flexWrap: "wrap",
    gap: 8,
  },
  progressBar: {
    height: 3,
    background: "#f1f5f9",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    background: "#6B1E1E",
    transition: "width 0.4s ease",
    borderRadius: 2,
  },
  queueList: {
    maxHeight: 400,
    overflowY: "auto",
  },
  queueItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 16px",
    borderBottom: "1px solid #f8f9fa",
    gap: 12,
  },
};

export default s;
